general:
    logoName: CM File Collectors
    isAdminLogin: false
    adminPassword: ""
    isAutoCreateM3u8: true
    language: zhCn
    notAllowServerOpenFile: false
    theme: default
    videoRateLimit:
        enabled: false
        requestsPerSecond: 5
        burst: 10
sqlite3:
    path: ./db/cm_collectors.db
    loggerLevel: info
system:
    serverHost: 0.0.0.0
    port: 12345
    database: sqlite3
    filePath: ./db/
    Env: debug
    responseMsgLanguage: en
    logFilePath: ./err.log
    logLevel: Error
    updateSoftConfig: https://objectstorageapi.ap-southeast-1.clawcloudrun.com/vj5i0ntw-cm-collectors-3/updateConfig/updateSoftConfig.json
scraper:
    useBrowserPath: false
    browserPath: ""
    logStatus: true
    logPath: ./scraper.log
    headless: true
    visitHome: false
    timeout: 30
play:
    playVideoFormats:
        - h264
        - vp8
        - vp9
        - av1
    playAudioFormats:
        - aac
        - opus
        - mp3
        - vorbis
        - pcm_s16le
        - pcm_s24le
jwt:
    expiresAt: 86400
    issuer: cmCollectors
    audience: cmCollectors
    subject: cmCollectors
    privateKeyPath: ./cert/jwtPrivate.key
    publicKeyPath: ./cert/jwtPublic.key
mysql:
    host: 127.0.0.1
    port: 3306
    db: cm_collectors
    user: root
    password: "123456"
    config: charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 3
    maxOpenConns: 20
    loggerLevel: info
cache:
    mode: freeCache
    redis:
        host: 127.0.0.1
        port: 6379
        password: xxxx
        db: 0
        defaultExpireSec: 3600
        minIdleConns: 5
        poolSize: 20
        connMaxIdleTime: 240
    freeCache:
        maxMemoryMB: 100
        defaultExpireSec: 3600
serverFileManagement:
    rootPath:
        - /
        - A:\
        - B:\
        - C:\
        - D:\
        - E:\
        - F:\
        - G:\
        - H:\
        - I:\
        - J:\
        - K:\
        - L:\
        - M:\
        - N:\
        - O:\
        - P:\
        - Q:\
        - R:\
        - S:\
        - T:\
        - U:\
        - V:\
        - W:\
        - X:\
        - Y:\
        - Z:\
taryMenu:
    - name: Chrome
      path: C:/Program Files/Google/Chrome/Application/chrome.exe
